version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: facebook
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
